registroPopTinpsag
registroPopTestadosag
registroPopInpector
registroPopContraparte

registroPopTransporte
registroPopProductor
registroPopConductor
registroPopComprador

registroPopPlanta2 planta externa
registroPopPlanta3 planta Propia

registroPopDfinal
registroPopMercado
registroPopRfinal
registroPopAgcarga
registroPopExportadora

registroPopTvehiculo
registroPopLcarga
registroPopLdestino

registroPopLaerea
registroPopAerolinia
registroPopAeronave
registroPopAcarga
registroPopAdestino

registroPopNaviera
registroPopNave
registroPopPcarga
registroPopPdestino

registroPopPvespecies
registroPopConsignatorio
registroPopNotificador
registroPopBroker
registroPopAaduana

registroPopTcontenedor
registroPopAtmosfera
registroPopFpago
registroPopMventa
registroPopCventa
registroPopTflete

NOMBREUSUARIO=<?php echo $NOMBREUSUARIOS; ?>&&